name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # يتم التشغيل عند الرفع إلى فرع main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # تشغيل العملية على نظام Linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Export (optional)
        run: |
          # If you need static export for GitHub Pages, ensure package.json
          # contains an "export" script that calls `next export`, then
          # uncomment the line below or keep it as a no-op.
          npm run export || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
